[project]
name = "scripts-transcribe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "assemblyai>=0.34.0",
    "glob2>=0.7",
    "os-sys>=0.9.1",
    "pprintpp>=0.4.0",
    "pydub>=0.25.1",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
